# Generated by Django 5.1.1 on 2024-09-13 03:49

import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.IntegerField()),
            ],
            options={
                'ordering': ('author',),
            },
        ),
        migrations.CreateModel(
            name='ModalityAssignment',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modality', models.CharField(choices=[('TEC', 'Tecnologico'), ('SW', 'Software'), ('DC', 'Didactico'), ('EV', 'Emprendedor Verde'), ('ES', 'Emprendedor Social'), ('ET', 'Emprendedor Tecnologico')], max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prototype',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('registry_number', models.CharField(max_length=10, unique=True)),
                ('modality', models.CharField(choices=[('TEC', 'Tecnologico'), ('SW', 'Software'), ('DC', 'Didactico'), ('EV', 'Emprendedor Verde'), ('ES', 'Emprendedor Social'), ('ET', 'Emprendedor Tecnologico')], max_length=3)),
                ('qualification', models.IntegerField(default=0, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='TeacherRoles',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roles', models.CharField(choices=[('AM', 'Asesor de metodologico'), ('AT', 'Asesor tecnico')], max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
