# Generated by Django 5.1.1 on 2024-09-13 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cores', '0001_initial'),
        ('prototypes', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.student'),
        ),
        migrations.AddField(
            model_name='modalityassignment',
            name='academic_level',
            field=models.ManyToManyField(to='cores.academiclevel'),
        ),
        migrations.AddField(
            model_name='prototype',
            name='members',
            field=models.ManyToManyField(to='prototypes.member'),
        ),
        migrations.AddField(
            model_name='prototype',
            name='teacher_methods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.teacher'),
        ),
        migrations.AddField(
            model_name='prototype',
            name='type_investigation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cores.typeinvestigation'),
        ),
        migrations.AddField(
            model_name='teacherroles',
            name='teacher_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teacher'),
        ),
        migrations.AddField(
            model_name='prototype',
            name='teacher_advisors',
            field=models.ManyToManyField(to='prototypes.teacherroles'),
        ),
    ]
