# Generated by Django 5.1.1 on 2024-10-05 03:58

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('budget_code', models.CharField(max_length=256)),
                ('cedual_profecional', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specialty', models.CharField(choices=[('TEP', 'TECNICO EN PROGRAMACION'), ('TEC', 'TECNICO EN CONTABILIDAD'), ('TESEB', 'TECNICO EN SECRETARIADO EJECUTIVO BILINGUE'), ('TECDEI', 'TECNICO EN CIENCIA DE DATOS E INFORMACION')], max_length=6)),
                ('school_control_number', models.CharField(max_length=256)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cores.academicgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
